### PR TITLE
Aligned the forgot password button

### PR DESCRIPTION
**Pull request by ShreeyashGarde**
Solved the alignment issue of forgot password button pls add the hactoberfest tag , any feedback is welcomed , thank you.

### CODE REVIEW

**Comment by RAHUL-DOGNEY** [comment]
Merged follow me

**Comment by RAHUL-DOGNEY** [comment]
Can you elaborate. Which thing you contribute

**Comment by RAHUL-DOGNEY** [comment]
Need to make proper folder name

**Comment by ShreeyashGarde** [comment]
In the forgot password button the forgot and password were very far away aligned so i aligned it according to the form
pls mark as hacktoberfest , thank you

**Pull request merged**
